# Generated by Django 6.0.7 on 2026-07-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfeature',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True, help_text='What problem did this project solve?'),
        ),
        migrations.AddField(
            model_name='project',
            name='commits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Lessons learned while building the project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='lines_of_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.TextField(blank=True, help_text='What was the final result?'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='Example: Full Stack Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='How was the problem solved?'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planning', 'Planning'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Completed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, help_text='Example: v1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, help_text='Example: 6 Weeks', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, default='fa-solid fa-code', help_text='Font Awesome icon class', max_length=100),
        ),
        migrations.CreateModel(
            name='DevelopmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-solid fa-code', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='projects.project')),
            ],
            options={
                'verbose_name': 'Development Stage',
                'verbose_name_plural': 'Development Stages',
                'ordering': ['order'],
            },
        ),
    ]
