# Generated by Django 6.0.7 on 2026-08-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='context',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
