# Generated by Django 6.0.7 on 2026-07-16 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/biography/')),
                ('alt_text', models.ImageField(blank=True, upload_to='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.biography')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
