# Generated by Django 6.0.7 on 2026-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_biographyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='icon',
            field=models.CharField(default='fa-solid fa-code', help_text='Font Awesome icon class', max_length=50),
        ),
    ]
