# Generated by Django 6.0.7 on 2026-07-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_techstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
