# Generated by Django 6.0.7 on 2026-08-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_techstack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.CharField(default='', help_text='Separate with commas.', max_length=250),
        ),
    ]
