# Generated by Django 6.0.7 on 2026-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_experience_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='technologies',
            field=models.CharField(help_text='Separate with commas.', max_length=250),
        ),
    ]
