# Generated by Django 6.0.7 on 2026-07-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
