# Generated by Django 6.0.7 on 2026-07-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_description_skill_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-percentage']},
        ),
    ]
