# Generated by Django 6.0.7 on 2026-07-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', '-percentage']},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Database', 'Database'), ('Tools', 'Tools'), ('Design', 'Design'), ('Other', 'Other')], default='Backend', max_length=30),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='fa-solid fa-code', help_text='Font Awesome class', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='projects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
